name: Publish and deploy Hedia service
# Builds and publishes Docker image to ghcr.io and Heroku Container Registry, and deploys container to Heroku app.
# Assumes that a Heroku app named 'hedia-{repository}-stg' exists, and which the provided Heroku API key has access to.

on:
  workflow_call:
    inputs:
      dyno-type:
        description: Heroku dyno type (web or worker)
        default: "worker"
        required: false
        type: string
      version-type:
        description: Version type (major|minor|patch). Can accept a list of labels, that contains a version type.
        default: "patch"
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      HEROKU_API_KEY:
        required: true
      GIT_CRYPT_KEY:
        required: true

permissions:
  pull-requests: read
  contents: write
  packages: write

jobs:
  publish-and-deploy-service:
    runs-on: ubuntu-latest

    steps:
      - name: Set version type from possible list of labels
        run: |
          case ${{ inputs.version-type }} in
              *"patch"*) type="patch" ;;
              *"minor"*) type="minor" ;;
              *"major"*) type="major" ;;
              *)
                echo "Version type is not set"
                exit 1
                ;;
          esac
          echo "VERSION_TYPE=${type}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set git identity
        run: |
          git config --global user.name "hedia-bot"
          git config --global user.email "github-action@users.noreply.github.com"

      - name: Decrypt config
        uses: sliteteam/github-action-git-crypt-unlock@1.1.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Bump version based on input
        run: |
          npm version ${{ env.VERSION_TYPE }}
          git push
          git push --tags

      - name: Extract package version
        run: |
          initialPackageJSON="$(sed -nE 's/^\s*"version": "([0-9]+.[0-9]+.[0-9]+).*?",$/\1/p' package.json)"
          echo "SERVICE_VERSION=${initialPackageJSON}" >> $GITHUB_ENV

      - name: Set app ID
        run: |
          repo_name=${{ github.event.repository.name }}
          app_name="${repo_name/service/svc}"
          app_id=hedia-${app_name}-stg
          echo "HEROKU_APP_ID=${app_id}" >> $GITHUB_ENV
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            BUILD_VERSION=${{ env.SERVICE_VERSION }}
          context: .
          push: true
          tags: |
            ghcr.io/hedia-team/${{ github.event.repository.name }}:latest
            ghcr.io/hedia-team/${{ github.event.repository.name }}:${{ env.SERVICE_VERSION }}
            registry.heroku.com/${{ env.HEROKU_APP_ID }}/${{ inputs.dyno-type }}

      - name: Deploy to staging
        run: |
          heroku container:release ${{ inputs.dyno-type }} -a ${{ env.HEROKU_APP_ID }}
          heroku ps:scale ${{ inputs.dyno-type}}=1 -a ${{ env.HEROKU_APP_ID }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
