name: Publish Docker Package

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      HEROKU_API_KEY:
        required: true
    inputs:
      dyno-type:
        type: string
        description: Heroku dyno type (web or worker)
        required: false
        default: "worker"

permissions:
  pull-requests: read
  contents: write

jobs:
  publish-docker-package:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Debug
        run: |
          echo ${{ github.event.repository.name }}
          echo ${{ inputs.dyno-type }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Login to Heroku registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Extract package version
        id: package-version
        run: |
          initialPackageJSON="$(sed -nE 's/^\s*"version": "([0-9]+.[0-9]+.[0-9]+).*?",$/\1/p' package.json)"
          echo ::set-output name=version::"$initialPackageJSON"
        shell: bash
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.package-version.outputs.version }}",
              sha: context.sha
            })
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            BUILD_VERSION=${{ steps.package-version.outputs.version }}
          context: .
          push: true
          tags: |
            ghcr.io/hedia-team/${{ github.event.repository.name }}:latest
            ghcr.io/hedia-team/${{ github.event.repository.name }}:${{ steps.package-version.outputs.version }}
            registry.heroku.com/${{ github.event.repository.name }}-staging/${{ inputs.dyno-type }}
      # - name: Deploy to staging
      #   id: deploy-to-staging
      #   run: |
      #     appID=${{ github.event.repository.name }}-staging
      #     echo $appID
      #     #heroku apps:info $appID
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
