name: test1

on:
  workflow_call:

permissions:
  pull-requests: read

jobs:
  validate-pr-labels:
    runs-on: ubuntu-latest

    steps:
      - name: test2
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: feature,feat,fix,test
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
