name: Validate PR title

on:
  workflow_call:

# permissions:
#   pull-requests: read

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: "^(((\\[\\d+\\.\\d+\\.\\d+\\])|(\\[Anytime\\]))\\s-\\s)?HDA-\\d+.*"
