name: Validate PR labels

on:
  pull_request:
    branches:
      - develop
    types: [opened, labeled, unlabeled]

permissions:
  pull-requests: read

jobs:
  validate-pr-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR labels
        uses: docker://agilepathway/pull-request-label-checker:v1.0.102
        with:
          any_of: feature,fix,test
          repo_token: ${{ secrets.GITHUB_TOKEN }}
